// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdzlcobzzglxqjxcfmgs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkemxjb2J6emdseHFqeGNmbWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTg3NjgsImV4cCI6MjA2OTE5NDc2OH0.3-yN2WyRyjBqf_PgjdUuX5y_jTvlzLzEuWvx1qARsnc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});